---
all:
  vars:
    ansible_user: testuser
    ansible_password: testpass
    ansible_become: yes
    ansible_become_method: sudo
    ansible_python_interpreter: /usr/bin/python3

  children:
    docker_test:
      hosts:
        target-ubuntu:
          ansible_host: 172.29.0.10
          ansible_port: 22
          os_family: Debian
          distribution: Ubuntu
          distribution_version: "22.04"

        target-debian:
          ansible_host: 172.29.0.11
          ansible_port: 22
          os_family: Debian
          distribution: Debian
          distribution_version: "12"

        target-arch:
          ansible_host: 172.29.0.12
          ansible_port: 22
          os_family: Archlinux
          distribution: Arch
          distribution_version: latest
