---
all:
  vars:
    ansible_user: testuser
    ansible_password: testpass
    ansible_become: yes
    ansible_become_method: sudo
    ansible_python_interpreter: /usr/bin/python3

  children:
    linux_test:
      hosts:
        target-arch:
          ansible_host: 172.29.0.10
          ansible_port: 22
          os_family: Archlinux
          distribution: Arch
          distribution_version: latest

    macos_test:
      hosts:
        target-macos:
          ansible_host: 127.0.0.1
          ansible_port: 2223
          ansible_user: admin
          os_family: Darwin
          distribution: macOS
          distribution_version: "14.0"
